### ISSUE TITLE
Can you offer me your newest test set ground truth?

### ISSUE THREAD

**Issue by gw00295652** [cs-chan/Total-Text-Dataset#27]
I can't find the newest test data set ground truth.
this is my email : taoju825538334@163.com
thanks!

**Comment by WeihongM** [comment]
Is the ground-truth of test data renewed also?
Or still the same as the legacy version?
@chunchet-ng @cs-chan

**Comment by ckchng** [comment]
Hi guys, thanks for the interest! We do not release a new version of the test set ground truth because 
1) there is no need of standardising the length of the ground truth vertices for testing purpose, it was proposed to facilitate training only,
2) a new version of ground truth would make the previous benchmarks irrelevant.

So if your intention is testing/benchmark only, there is no need for the new ground truth. Do let me know if you intend to use it for other unforeseen purposes, and we shall discuss further. Cheers!

**Comment by WeihongM** [comment]
@ckchng  Thanks for your reply.
I am not familiar with this dataset. Can you share the main difference when we use fixed 10 vertices to represent the polygon compared with former ground-truth?

**Comment by ckchng** [comment]
The number of vertices in the former ground-truth is unfixed. It could be a problem if you want to train a regression-based deep nets. The new ground-truth is annotated with a guided mechanism to remove biases too. 

It's all described in the following paper
https://link.springer.com/article/10.1007/s10032-019-00334-z

**Comment by WeihongM** [comment]
Got it, thanks for your reply.
